# Generated by Django 4.0.5 on 2022-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closedbracketfinal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
